### PR TITLE
Translation to English - United States

### PR DESCRIPTION
**Pull request by Djuki**
Add English USA translation for request #11

### CODE REVIEW

**Comment by drdrjojo** [comment]
Original daysWeek values are starting with Sunday!

**Comment by Djuki** [comment]
@drdrjojo @Jeconias It is fixed, please review.

**Comment by Jeconias** [comment]
> @drdrjojo @Jeconias It is fixed, please review.

Sorry! You can change file for new pattern? [Look here](https://github.com/Jeconias/calendarjs/blob/master/src/languages/deDE.js)

**Comment by Djuki** [comment]
@Jeconias Changed.

**Pull request merged**
